### ISSUE TITLE
IPv6?

### ISSUE THREAD

**Issue by asloan7** [awslabs/ecs-refarch-cloudformation#19]
It would be great if this could handle IPv6/dualstack traffic

**Comment by wichert** [comment]
Unfortunately CF itself does not have the necessary support at this point in time.

**Comment by asloan7** [comment]
I think CF could set the necessary settings, but I found NAT gateway can only do IPv4 currently, and an egress-only gateway could be set up for IPv6 only - that's a lot more to jam in to the CF template

**Comment by wichert** [comment]
My experience is that you can configure some things with CF, but not enough to get you anywhere useful. For example generating IPv6 ranges for your subnets is not possible without resorting to things like custom resources.

**Comment by ranman** [comment]
I think http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnetcidrblock.html can associate the ranges? Generating them should be pretty easy too?

**Comment by wichert** [comment]
Generating them is exactly the part that is completely missing.

**Comment by PaulMaddox** [comment]
Closing this issue for now - feel free to re-open once CF has support.
