### ISSUE TITLE
EC2 instance registered on ECS default cluster

### ISSUE THREAD

**Issue by MatteCarra** [awslabs/ecs-refarch-cloudformation#23]
I don't know how to reproduce this but a newly created ec2 instance registered itself on ECS default cluster instead of the right one.
Why don't you set ECS_CLUSTER in ecs.config in UserData?

**Comment by JasonSwindle** [comment]
Howdy,

Are you still having this issue?  Looking at the template, on this line:

https://github.com/awslabs/ecs-refarch-cloudformation/blob/18fd28c6c2bc054694c2ab9670c98da06b6171af/infrastructure/ecs-cluster.yaml#L138

the ECS Cluster is passed to the ```ecs.config``` and should be read by the ECS Agent.
