### ISSUE TITLE
Simple question on ALB and NAT gateway traffic

### ISSUE THREAD

**Issue by johntwei** [awslabs/ecs-refarch-cloudformation#31]
In the document, I saw these:
**•A pair of NAT gateways (one in each zone) to handle outbound traffic.
•An Application Load Balancer (ALB) to the public subnets to handle inbound traffic.**
I believe these two statements are independent. Meaning:
- internet access request will go out through NAT gateway
- external request from internet to ESC services will come through ALB, and **response** get sent back through ALB as well.
It does not mean that external request will be returned through NAT gateway. Is this correct?

**Comment by wichert** [comment]
Correct.
