### ISSUE TITLE
How to update container instances in production?

### ISSUE THREAD

**Issue by davidham** [awslabs/ecs-refarch-cloudformation#32]
What's the best way to update the container instances--new size, new AMI? (Thanks for the email notifications about the new ECS optimized AMIs by the way.) Seems like we could update the launch configuration AMI, but I don't want to interrupt existing instances. Would I need to set a `DeletionPolicy` on the EC2s, update the stack to the new instances, and then go in and manually delete the old ones?

**Comment by PaulMaddox** [comment]
You can just change the AMI, or instance family/size in the CloudFormation template, then just update the CloudFormation stack. CloudFormation will perform a rolling update of your ECS instances, updating them one-at-a-time (by default). 

This works as the Auto Scaling Group of ECS instances deployed includes an [UpdatePolicy](https://aws.amazon.com/premiumsupport/knowledge-center/auto-scaling-group-rolling-updates/).

You can see this defined here:
https://github.com/awslabs/ecs-refarch-cloudformation/blob/master/infrastructure/ecs-cluster.yaml#L100-L111
