### ISSUE TITLE
Stack getting rolled back automatically

### ISSUE THREAD

**Issue by Dawny33** [awslabs/ecs-refarch-cloudformation#43]
Deployed the CloudFormation stack as is, in the `us-east-1` region, the process got rolled back automatically after some time.

Image for reference:

<img width="1394" alt="screen shot 2018-01-23 at 5 15 17 pm" src="https://user-images.githubusercontent.com/4637008/35274139-05e41952-0061-11e8-9e08-e12eb0e3867b.png">

[PS: I have not initiated any rollbacks]

**Comment by PaulMaddox** [comment]
Hi @Dawny33,

The CloudFormation templates included within this repository include deploying new IAM roles.

CloudFormation by default, refuses to create IAM roles unless you specifically tick a box (or provide a cli flag) to allow it to do so.

If deploying via the CLI, add the following flag:
```
$ aws cloudformation create-stack --stack-name <name> ......... --capabilities CAPABILITY_IAM
```

If deploying via the AWS Management Console, make sure to tick this box on the last page of the CloudFormation console wizard when creating a stack:

![image](https://user-images.githubusercontent.com/4678446/35277822-e27ddf8c-003f-11e8-960f-4d79e26df7af.png)
