### ISSUE TITLE
Deploying in a private subnet

### ISSUE THREAD

**Issue by dls314** [awslabs/ecs-refarch-cloudformation#58]
I've tried deploying these templates into a pre-existing VPC with private subnets (which can route to a NAT gateway).

- security-groups.yaml
- load-balancers.yaml
- ecs-cluster.yaml

The instances don't register to the cluster (they appear in the default cluster in the ECS control panel) and the stack reverts after 15 minutes.

Has anyone tried using these templates like this?

**Comment by PaulMaddox** [comment]
Have you checked that outbound internet access is possible from your private subnets?

This reference architecture has NAT Gateways in the public subnets to facilitate connectivity from the EC2 instances out to the ECS service endpoint.

**Comment by dls314** [comment]
I had an S3 VPC endpoint provisioned and it seems to keep the yum update in the ecs-cluster template from working correctly.
