### ISSUE TITLE
unable to login to Ec2

### ISSUE THREAD

**Issue by Ponrajk22** [awslabs/ecs-refarch-cloudformation#62]
May i know how i can map my existing keypair to enable logging to Ec2

**Comment by PaulMaddox** [comment]
By default, for security reasons SSH access is disabled (well, to be specific, it's not configured with an SSH key).

You have two options:

1. The ECS hosts have AWS SSM enabled, which allows you to easily run commands on the hosts and gather results, without needing SSH. You can go to the EC2 console and click on `Run Command` to do this.

2. Update the `LaunchConfiguration` in [infrastructure/ecs-cluster.yaml](infrastructure/ecs-cluster.yaml) to include a [`KeyName`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html#cfn-as-launchconfig-keyname) property, pointing to your EC2 Keypair name.

Thanks
