### ISSUE TITLE
Implement connection draining

### ISSUE THREAD

**Issue by PaulMaddox** [awslabs/ecs-refarch-cloudformation#7]
Implement automatic connection draining on ECS hosts, via Auto Scaling Group lifecycle events.

https://aws.amazon.com/blogs/compute/how-to-automate-container-instance-draining-in-amazon-ecs/

Pull requests welcome, otherwise I will try and look at implementing this over the coming weeks.

**Comment by ktruckenmiller** [comment]
How would you want this? Custom lifecycle hook -> SNS -> Step Function? Or is it easier than that?

**Comment by JasonSwindle** [comment]
This should be addressed by PR #59
