### ISSUE TITLE
Missing LogGroup creation in ecs-cluster.yaml

### ISSUE THREAD

**Issue by pgrzesik** [awslabs/ecs-refarch-cloudformation#73]
Hello,

is that the correct behavior that during creation of stack from `ecs-cluster.yaml` template, the LogGroup is not created ? In configuration, there're references to LogGroups e.g. `log_group_name = ${ECSCluster}-/var/log/dmesg`, but those log groups are not created. 

Should they be created automatically by the instance or should I add LogGroup creation to the template ? 

Regards,
Piotr

**Comment by wichert** [comment]
They are created automatically

**Comment by pgrzesik** [comment]
That's what I would expect and that's correct behavior, as it turns out, I made a little mistake in my own CF template :) Sorry for bothering and thanks for preparing this great template.
