### ISSUE TITLE
ECS is not created

### ISSUE THREAD

**Issue by ghost** [awslabs/ecs-refarch-cloudformation#8]
I ran your cloudformation templates. The stack is created successfully, but no ECS is created. There is no service, no task definition created. But there is no error. Seems your ecs-cluster yaml is totally ignored.

**Comment by PaulMaddox** [comment]
Hi,

I can't replicate this. What region are you using?
Can you send me the CloudFormation stack ID? pmaddox AT amazon DOT com

Thanks.

**Comment by ghost** [comment]
Hi, I have got my ecs cloudformation template running. You can close this case. Thanks!
