### ISSUE TITLE
Unused role in template

### ISSUE THREAD

**Issue by pkaramol** [awslabs/ecs-refarch-cloudformation#83]
This [ECSServiceAutoScalingRole](https://github.com/aws-samples/ecs-refarch-cloudformation/blob/ecacd7a1b6a95e9d1263d42989b3bd6dab7b574f/infrastructure/ecs-cluster.yaml#L308) does not seem to be used anywhere. Is it attached somewhere?

On the other hand for example the [ECSRole](https://github.com/aws-samples/ecs-refarch-cloudformation/blob/ecacd7a1b6a95e9d1263d42989b3bd6dab7b574f/infrastructure/ecs-cluster.yaml#L227) is attached to the [ECSInstanceProfile](https://github.com/aws-samples/ecs-refarch-cloudformation/blob/ecacd7a1b6a95e9d1263d42989b3bd6dab7b574f/infrastructure/ecs-cluster.yaml#L301)

**Comment by kaikuchn** [comment]
It is passed to the [Website-Service](https://github.com/aws-samples/ecs-refarch-cloudformation/blob/ecacd7a1b6a95e9d1263d42989b3bd6dab7b574f/master.yaml#L83) and [there](https://github.com/aws-samples/ecs-refarch-cloudformation/blob/master/services/website-service/service.yaml#L158) it's used for the `ServiceScalableTarget`.
