### ISSUE TITLE
Default to latest ECS-Optimized AMI

### ISSUE THREAD

**Issue by StevenAskwith** [awslabs/ecs-refarch-cloudformation#89]
# Default to latest ECS-Optimized AMI
Added ECSAMI parameter which defaults to latest ECS-Optimized AMI
Removed legacy AMI Mappings
Pull Request #88 

Thanks @mrichman for the pointer :)

**Comment by mrichman** [comment]
You're welcome!

**Comment by StevenAskwith** [comment]
Closing as duplicate of #61
